# Site settings
title: Gurnoor Singh
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gurnoor.me/"

# User settings
username: Gurnoor Singh
user_description: An autodidactic ambivert, Linux lover, AI Enthusiast, Wanderluster.
user_title:  AI & Deep Learning Enthusiast
email: 
#3twitter_username: lorem_ipsum
#github_username:  lorem_ipsum
#gplus_username:  lorem_ipsum

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
