# Site settings
title: Gurnoor Singh
description: A blog about lorem ipsum dolor sit amet
baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://gurnoor.me/particle/"

# User settings
username: Gurnoor Singh
user_description: An autodidactic ambivert, Linux lover, AI Enthusiast, Wanderluster.
user_title:  AI & Deep Learning Enthusiast
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
